name: "Vprofile IAC"
on: 
    push:
        branches:
            - main
            - stage
        paths:
            - terraform/**
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCCESS_KEY}}
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
    EKS_CLUSTER: vprofile-eks

jobs:
    terraform:
        name: 'apply terraform code changes'
        runs-on: macos-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        
        steps:
            - name: checkout the source code
              uses: actions/checkout@v4
              
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Initialize Terraform
              id: init
              run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

            - name: Terraform format
              id: fmt
              run: terraform fmt -check 
      
            - name: Validate Terraform
              id: validate
              run: terraform validate
      
            - name: Plan Terraform
              id: plan
              run: terraform plan -no-color -input=false -out planfile
              continue-on-error: true

            - name: Terraform plan status
              if: steps.plan.outcome == 'failure'
              run: exit 1
      
            - name: Apply Terraform
              if: github.event_name == 'push'
              run: terraform apply -auto-approve tfplan              